import React, { createContext, useContext, useState } from 'react';

const T = {
    en: {
        /* Nav */
        dashboard: 'Dashboard', market: 'Market', insights: 'Insights', settings: 'Settings',
        profile: 'Profile', signOut: 'Sign out', backToDashboard: 'Back to Dashboard',
        /* Dashboard welcome */
        goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening',
        aiSubtitle: 'Select your crop and location to get AI-powered market intelligence.',
        liveMarketData: 'Live Market Data Active',
        /* Controls */
        selectCrop: 'SELECT CROP', location: 'LOCATION', runAnalysis: 'Run Analysis', analyzing: 'Analyzing…',
        locationPlaceholder: 'e.g. Punjab, India',
        /* Stat cards */
        priceTrend: 'Price Trend', temperature: 'Temperature', humidity: 'Humidity', bestMandi: 'Best Mandi',
        /* Weather */
        weatherForecast: 'Weather Forecast', live: 'Live',
        rainfall: 'Rainfall', wind: 'Wind', uvIndex: 'UV Index',
        /* Spoilage */
        spoilageRisk: 'Spoilage Risk', risk: 'Risk',
        /* Price prediction */
        pricePrediction: 'Price Prediction', dayForecast: '14-day AI forecast for',
        over14d: 'over 14d',
        /* Best Mandi */
        bestMandiOpp: 'Best Mandi Opportunity',
        mandiSubtitle: 'Optimal market based on distance, price & demand',
        confidence: 'Confidence', predictedPrice: 'Predicted Price', expProfit: 'Exp. Profit/Acre',
        aiConfidence: 'AI Confidence', navigateToMandi: 'Navigate to Mandi',
        /* AI Insights */
        aiInsights: 'AI Insights', gptPowered: 'GPT-Powered',
        defaultInsight: 'Based on historical trends and current demand spikes in the Ludhiana region, Khanna Mandi is showing a 12% higher rate compared to local averages. The upcoming rainfall predicted in 3 days might disrupt logistics, suggesting an optimal selling window within the next 48 hours to maximize profit.',
        /* Tags */
        demandSpike: 'Demand Spike', weatherRisk: 'Weather Risk', historicalHigh: 'Historical High',
        priceWindow: 'Price Window', marketTrend: 'Market Trend',
        /* Settings */
        saveSettings: 'Save Settings', saving: 'Saving…',
        notifications: 'Notifications', displayLanguage: 'Display & Language',
        privacyData: 'Privacy & Data', dangerZone: 'Danger Zone',
        theme: 'Theme', language: 'Language', languageSub: 'Choose your preferred display language',
        light: 'Light', system: 'System', dark: 'Dark',
        emailAlerts: 'Email Alerts', emailAlertsSub: 'Receive price and market updates via email',
        smsAlerts: 'SMS Alerts', smsAlertsSub: 'Get critical alerts directly to your phone',
        priceDropAlerts: 'Price Drop Alerts', priceDropAlertsSub: 'Notify me when crop prices fall significantly',
        weeklyReport: 'Weekly Market Report', weeklyReportSub: 'Summary email every Monday morning',
        marketNews: 'Market News', marketNewsSub: 'Breaking agricultural news and policy updates',
        shareData: 'Share Usage Data', shareDataSub: 'Help us improve CropSense with anonymous analytics',
        analytics: 'Analytics', analyticsSub: 'Allow performance and error tracking',
        locationTracking: 'Location Tracking', locationTrackingSub: 'Auto-detect your location for weather accuracy',
        deleteAccount: 'Delete Account', deleteAccountSub: 'Permanently delete your account and all associated data. This action cannot be undone.',
        delete: 'Delete', cancel: 'Cancel', confirmDelete: 'Delete your account?',
        confirmDeleteBody: 'All your data, analyses, and preferences will be permanently removed. This cannot be undone.',
        /* Market */
        marketPrices: 'Market Prices', commodityPrices: 'Commodity Prices',
        lastUpdated: 'Last updated', viewAll: 'View All', pricePerQtl: '₹/Qtl',
        searchPlaceholder: 'Search crop or mandi…',
        topGainer: 'Top Gainer', topLoser: 'Top Loser', activeMandis: 'Active Mandis', totalVolume: 'Total Volume',
        sixMonthTrend: '6-Month Price Trend', topMandisByVol: 'Top Mandis by Volume',
        marketNewsAlerts: 'Market News & Alerts',
        dataFooter: 'Data updated every 30 minutes · CropSense AI © ',
        pricesIndicative: '· Prices are indicative',
        /* Profile */
        editProfile: 'Edit Profile', fullName: 'Full Name', email: 'Email',
        phoneNumber: 'Phone Number', locationLabel: 'Location', preferredCrop: 'Preferred Crop',
        shortBio: 'Short Bio', bioPlaceholder: 'Tell us a little about your farm…',
        accountInfo: 'Account Info', accountType: 'ACCOUNT TYPE', memberSince: 'MEMBER SINCE',
        analysesRun: 'ANALYSES RUN', avgAccuracy: 'AVG. ACCURACY',
        activeFarmer: 'Active Farmer', managePlan: 'Manage Plan', saveProfile: 'Save Profile',
        savingProfile: 'Saving…',
    },
    hi: {
        dashboard: 'डैशबोर्ड', market: 'बाज़ार', insights: 'अंतर्दृष्टि', settings: 'सेटिंग्स',
        profile: 'प्रोफ़ाइल', signOut: 'साइन आउट', backToDashboard: 'डैशबोर्ड पर वापस जाएं',
        goodMorning: 'सुप्रभात', goodAfternoon: 'नमस्कार', goodEvening: 'शुभ संध्या',
        aiSubtitle: 'AI-आधारित बाज़ार जानकारी के लिए अपनी फसल और स्थान चुनें।',
        liveMarketData: 'लाइव बाज़ार डेटा सक्रिय',
        selectCrop: 'फसल चुनें', location: 'स्थान', runAnalysis: 'विश्लेषण करें', analyzing: 'विश्लेषण हो रहा है…',
        locationPlaceholder: 'जैसे: पंजाब, भारत',
        priceTrend: 'मूल्य रुझान', temperature: 'तापमान', humidity: 'आर्द्रता', bestMandi: 'सर्वश्रेष्ठ मंडी',
        weatherForecast: 'मौसम पूर्वानुमान', live: 'लाइव',
        rainfall: 'वर्षा', wind: 'हवा', uvIndex: 'UV सूचकांक',
        spoilageRisk: 'खराब होने का जोखिम', risk: 'जोखिम',
        pricePrediction: 'मूल्य पूर्वानुमान', dayForecast: '14-दिन AI पूर्वानुमान',
        over14d: '14 दिनों में',
        bestMandiOpp: 'सर्वश्रेष्ठ मंडी अवसर',
        mandiSubtitle: 'दूरी, मूल्य और मांग के आधार पर सर्वोत्तम बाज़ार',
        confidence: 'विश्वास', predictedPrice: 'अनुमानित मूल्य', expProfit: 'अनु. लाभ/एकड़',
        aiConfidence: 'AI विश्वास', navigateToMandi: 'मंडी पर जाएं',
        aiInsights: 'AI अंतर्दृष्टि', gptPowered: 'GPT-संचालित',
        defaultInsight: 'ऐतिहासिक रुझानों और वर्तमान मांग के आधार पर, खन्ना मंडी स्थानीय औसत से 12% अधिक दर दिखा रही है। अगले 3 दिनों में बारिश की संभावना है, इसलिए अधिकतम लाभ के लिए अगले 48 घंटों में बेचना उचित होगा।',
        demandSpike: 'मांग वृद्धि', weatherRisk: 'मौसम जोखिम', historicalHigh: 'ऐतिहासिक उच्च',
        priceWindow: 'मूल्य अवसर', marketTrend: 'बाज़ार रुझान',
        saveSettings: 'सेटिंग्स सहेजें', saving: 'सहेजा जा रहा है…',
        notifications: 'सूचनाएं', displayLanguage: 'प्रदर्शन और भाषा',
        privacyData: 'गोपनीयता और डेटा', dangerZone: 'खतरनाक क्षेत्र',
        theme: 'थीम', language: 'भाषा', languageSub: 'अपनी पसंदीदा भाषा चुनें',
        light: 'हल्का', system: 'सिस्टम', dark: 'गहरा',
        emailAlerts: 'ईमेल अलर्ट', emailAlertsSub: 'ईमेल पर मूल्य और बाज़ार अपडेट प्राप्त करें',
        smsAlerts: 'SMS अलर्ट', smsAlertsSub: 'फोन पर महत्वपूर्ण अलर्ट प्राप्त करें',
        priceDropAlerts: 'मूल्य गिरावट अलर्ट', priceDropAlertsSub: 'फसल की कीमत गिरने पर सूचित करें',
        weeklyReport: 'साप्ताहिक बाज़ार रिपोर्ट', weeklyReportSub: 'हर सोमवार सुबह सारांश ईमेल',
        marketNews: 'बाज़ार समाचार', marketNewsSub: 'कृषि समाचार और नीति अपडेट',
        shareData: 'उपयोग डेटा साझा करें', shareDataSub: 'अनाम विश्लेषण से CropSense सुधारने में मदद करें',
        analytics: 'एनालिटिक्स', analyticsSub: 'प्रदर्शन और त्रुटि ट्रैकिंग की अनुमति दें',
        locationTracking: 'स्थान ट्रैकिंग', locationTrackingSub: 'मौसम सटीकता के लिए स्थान स्वत: पहचानें',
        deleteAccount: 'खाता हटाएं', deleteAccountSub: 'आपका खाता और सभी डेटा स्थायी रूप से हटाया जाएगा। इसे पूर्ववत नहीं किया जा सकता।',
        delete: 'हटाएं', cancel: 'रद्द करें', confirmDelete: 'अपना खाता हटाएं?',
        confirmDeleteBody: 'आपके सभी डेटा, विश्लेषण और प्राथमिकताएं स्थायी रूप से हटा दी जाएंगी।',
        marketPrices: 'बाज़ार भाव', commodityPrices: 'वस्तु कीमतें',
        lastUpdated: 'अंतिम अपडेट', viewAll: 'सभी देखें', pricePerQtl: '₹/क्विंटल',
        searchPlaceholder: 'फसल या मंडी खोजें…',
        topGainer: 'सबसे अधिक बढ़त', topLoser: 'सबसे अधिक गिरावट', activeMandis: 'सक्रिय मंडियां', totalVolume: 'कुल मात्रा',
        sixMonthTrend: '6 माह मूल्य रुझान', topMandisByVol: 'मात्रा के अनुसार शीर्ष मंडियां',
        marketNewsAlerts: 'बाज़ार समाचार और अलर्ट',
        dataFooter: 'डेटा हर 30 मिनट में अपडेट · CropSense AI © ',
        pricesIndicative: '· कीमतें सांकेतिक हैं',
        editProfile: 'प्रोफ़ाइल संपादित करें', fullName: 'पूरा नाम', email: 'ईमेल',
        phoneNumber: 'फोन नंबर', locationLabel: 'स्थान', preferredCrop: 'पसंदीदा फसल',
        shortBio: 'संक्षिप्त परिचय', bioPlaceholder: 'अपने खेत के बारे में बताएं…',
        accountInfo: 'खाता जानकारी', accountType: 'खाता प्रकार', memberSince: 'सदस्यता तिथि',
        analysesRun: 'विश्लेषण किए', avgAccuracy: 'औसत सटीकता',
        activeFarmer: 'सक्रिय किसान', managePlan: 'प्लान प्रबंधित करें', saveProfile: 'प्रोफ़ाइल सहेजें',
        savingProfile: 'सहेजा जा रहा है…',
    },
    pa: {
        dashboard: 'ਡੈਸ਼ਬੋਰਡ', market: 'ਬਾਜ਼ਾਰ', insights: 'ਸੂਝ', settings: 'ਸੈਟਿੰਗਾਂ',
        profile: 'ਪ੍ਰੋਫਾਈਲ', signOut: 'ਸਾਈਨ ਆਊਟ', backToDashboard: 'ਡੈਸ਼ਬੋਰਡ ਤੇ ਵਾਪਸ',
        goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ', goodAfternoon: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ', goodEvening: 'ਸ਼ੁਭ ਸ਼ਾਮ',
        aiSubtitle: 'AI-ਆਧਾਰਿਤ ਬਾਜ਼ਾਰ ਜਾਣਕਾਰੀ ਲਈ ਆਪਣੀ ਫ਼ਸਲ ਅਤੇ ਟਿਕਾਣਾ ਚੁਣੋ।',
        liveMarketData: 'ਲਾਈਵ ਬਾਜ਼ਾਰ ਡੇਟਾ ਸਕਿਰਿਆ',
        selectCrop: 'ਫ਼ਸਲ ਚੁਣੋ', location: 'ਟਿਕਾਣਾ', runAnalysis: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ', analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ…',
        locationPlaceholder: 'ਜਿਵੇਂ: ਪੰਜਾਬ, ਭਾਰਤ',
        priceTrend: 'ਕੀਮਤ ਰੁਝਾਨ', temperature: 'ਤਾਪਮਾਨ', humidity: 'ਨਮੀ', bestMandi: 'ਸਭ ਤੋਂ ਵਧੀਆ ਮੰਡੀ',
        weatherForecast: 'ਮੌਸਮ ਭਵਿੱਖਬਾਣੀ', live: 'ਲਾਈਵ',
        rainfall: 'ਬਾਰਿਸ਼', wind: 'ਹਵਾ', uvIndex: 'ਯੂਵੀ ਸੂਚਕਾਂਕ',
        spoilageRisk: 'ਖਰਾਬ ਹੋਣ ਦਾ ਜੋਖਮ', risk: 'ਜੋਖਮ',
        pricePrediction: 'ਕੀਮਤ ਭਵਿੱਖਬਾਣੀ', dayForecast: '14-ਦਿਨ AI ਭਵਿੱਖਬਾਣੀ',
        over14d: '14 ਦਿਨਾਂ ਵਿੱਚ',
        bestMandiOpp: 'ਸਭ ਤੋਂ ਵਧੀਆ ਮੰਡੀ ਮੌਕਾ',
        mandiSubtitle: 'ਦੂਰੀ, ਕੀਮਤ ਅਤੇ ਮੰਗ ਦੇ ਆਧਾਰ ਤੇ ਸਰਵੋਤਮ ਬਾਜ਼ਾਰ',
        confidence: 'ਭਰੋਸਾ', predictedPrice: 'ਅਨੁਮਾਨਿਤ ਕੀਮਤ', expProfit: 'ਅਨੁ. ਲਾਭ/ਏਕੜ',
        aiConfidence: 'AI ਭਰੋਸਾ', navigateToMandi: 'ਮੰਡੀ ਵੱਲ ਜਾਓ',
        aiInsights: 'AI ਸੂਝ', gptPowered: 'GPT-ਸੰਚਾਲਿਤ',
        defaultInsight: 'ਇਤਿਹਾਸਕ ਰੁਝਾਨਾਂ ਅਤੇ ਮੌਜੂਦਾ ਮੰਗ ਦੇ ਆਧਾਰ ਤੇ ਖੰਨਾ ਮੰਡੀ ਸਥਾਨਕ ਔਸਤ ਤੋਂ 12% ਵੱਧ ਦਰ ਦਿਖਾ ਰਹੀ ਹੈ।',
        demandSpike: 'ਮੰਗ ਵਾਧਾ', weatherRisk: 'ਮੌਸਮ ਜੋਖਮ', historicalHigh: 'ਇਤਿਹਾਸਕ ਉੱਚ',
        priceWindow: 'ਕੀਮਤ ਮੌਕਾ', marketTrend: 'ਬਾਜ਼ਾਰ ਰੁਝਾਨ',
        saveSettings: 'ਸੈਟਿੰਗਾਂ ਸੁਰੱਖਿਅਤ ਕਰੋ', saving: 'ਸੁਰੱਖਿਅਤ ਹੋ ਰਿਹਾ ਹੈ…',
        notifications: 'ਸੂਚਨਾਵਾਂ', displayLanguage: 'ਡਿਸਪਲੇ ਅਤੇ ਭਾਸ਼ਾ',
        privacyData: 'ਗੋਪਨੀਯਤਾ ਅਤੇ ਡੇਟਾ', dangerZone: 'ਖ਼ਤਰਨਾਕ ਖੇਤਰ',
        theme: 'ਥੀਮ', language: 'ਭਾਸ਼ਾ', languageSub: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ',
        light: 'ਹਲਕਾ', system: 'ਸਿਸਟਮ', dark: 'ਗਹਿਰਾ',
        emailAlerts: 'ਈਮੇਲ ਅਲਰਟ', emailAlertsSub: 'ਈਮੇਲ ਰਾਹੀਂ ਕੀਮਤ ਅਪਡੇਟ ਪ੍ਰਾਪਤ ਕਰੋ',
        smsAlerts: 'SMS ਅਲਰਟ', smsAlertsSub: 'ਫੋਨ ਤੇ ਮਹੱਤਵਪੂਰਨ ਅਲਰਟ ਪ੍ਰਾਪਤ ਕਰੋ',
        priceDropAlerts: 'ਕੀਮਤ ਗਿਰਾਵਟ ਅਲਰਟ', priceDropAlertsSub: 'ਫ਼ਸਲ ਦੀ ਕੀਮਤ ਡਿੱਗਣ ਤੇ ਸੂਚਿਤ ਕਰੋ',
        weeklyReport: 'ਹਫ਼ਤਾਵਾਰੀ ਬਾਜ਼ਾਰ ਰਿਪੋਰਟ', weeklyReportSub: 'ਹਰ ਸੋਮਵਾਰ ਸਵੇਰੇ ਸਾਰਾਂਸ਼ ਈਮੇਲ',
        marketNews: 'ਬਾਜ਼ਾਰ ਖ਼ਬਰਾਂ', marketNewsSub: 'ਖੇਤੀ ਖ਼ਬਰਾਂ ਅਤੇ ਨੀਤੀ ਅਪਡੇਟ',
        shareData: 'ਵਰਤੋਂ ਡੇਟਾ ਸਾਂਝਾ ਕਰੋ', shareDataSub: 'ਅਗਿਆਤ ਵਿਸ਼ਲੇਸ਼ਣ ਨਾਲ CropSense ਬਿਹਤਰ ਬਣਾਓ',
        analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ', analyticsSub: 'ਪ੍ਰਦਰਸ਼ਨ ਅਤੇ ਗਲਤੀ ਟਰੈਕਿੰਗ ਦੀ ਆਗਿਆ ਦਿਓ',
        locationTracking: 'ਸਥਾਨ ਟਰੈਕਿੰਗ', locationTrackingSub: 'ਮੌਸਮ ਸ਼ੁੱਧਤਾ ਲਈ ਸਥਾਨ ਆਪਣੇ ਆਪ ਪਛਾਣੋ',
        deleteAccount: 'ਖਾਤਾ ਮਿਟਾਓ', deleteAccountSub: 'ਤੁਹਾਡਾ ਖਾਤਾ ਅਤੇ ਸਾਰਾ ਡੇਟਾ ਸਥਾਈ ਤੌਰ ਤੇ ਮਿਟਾਇਆ ਜਾਵੇਗਾ।',
        delete: 'ਮਿਟਾਓ', cancel: 'ਰੱਦ ਕਰੋ', confirmDelete: 'ਆਪਣਾ ਖਾਤਾ ਮਿਟਾਓ?',
        confirmDeleteBody: 'ਤੁਹਾਡੇ ਸਾਰੇ ਡੇਟਾ ਅਤੇ ਤਰਜੀਹਾਂ ਸਥਾਈ ਤੌਰ ਤੇ ਹਟਾ ਦਿੱਤੀਆਂ ਜਾਣਗੀਆਂ।',
        marketPrices: 'ਬਾਜ਼ਾਰ ਭਾਅ', commodityPrices: 'ਵਸਤੂ ਕੀਮਤਾਂ',
        lastUpdated: 'ਆਖਰੀ ਅੱਪਡੇਟ', viewAll: 'ਸਭ ਦੇਖੋ', pricePerQtl: '₹/ਕੁਇੰਟਲ',
        searchPlaceholder: 'ਫ਼ਸਲ ਜਾਂ ਮੰਡੀ ਖੋਜੋ…',
        topGainer: 'ਸਭ ਤੋਂ ਵੱਧ ਵਾਧਾ', topLoser: 'ਸਭ ਤੋਂ ਵੱਧ ਗਿਰਾਵਟ', activeMandis: 'ਸਕਿਰਿਆ ਮੰਡੀਆਂ', totalVolume: 'ਕੁੱਲ ਮਾਤਰਾ',
        sixMonthTrend: '6 ਮਹੀਨੇ ਕੀਮਤ ਰੁਝਾਨ', topMandisByVol: 'ਮਾਤਰਾ ਅਨੁਸਾਰ ਸਿਖਰ ਮੰਡੀਆਂ',
        marketNewsAlerts: 'ਬਾਜ਼ਾਰ ਖ਼ਬਰਾਂ ਅਤੇ ਅਲਰਟ',
        dataFooter: 'ਡੇਟਾ ਹਰ 30 ਮਿੰਟ ਵਿੱਚ ਅੱਪਡੇਟ · CropSense AI © ',
        pricesIndicative: '· ਕੀਮਤਾਂ ਸੰਕੇਤਕ ਹਨ',
        editProfile: 'ਪ੍ਰੋਫਾਈਲ ਸੋਧੋ', fullName: 'ਪੂਰਾ ਨਾਮ', email: 'ਈਮੇਲ',
        phoneNumber: 'ਫੋਨ ਨੰਬਰ', locationLabel: 'ਟਿਕਾਣਾ', preferredCrop: 'ਪਸੰਦੀਦਾ ਫ਼ਸਲ',
        shortBio: 'ਸੰਖੇਪ ਜਾਣ-ਪਛਾਣ', bioPlaceholder: 'ਆਪਣੇ ਖੇਤ ਬਾਰੇ ਦੱਸੋ…',
        accountInfo: 'ਖਾਤਾ ਜਾਣਕਾਰੀ', accountType: 'ਖਾਤਾ ਕਿਸਮ', memberSince: 'ਮੈਂਬਰਸ਼ਿਪ ਮਿਤੀ',
        analysesRun: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤੇ', avgAccuracy: 'ਔਸਤ ਸ਼ੁੱਧਤਾ',
        activeFarmer: 'ਸਕਿਰਿਆ ਕਿਸਾਨ', managePlan: 'ਪਲਾਨ ਪ੍ਰਬੰਧਿਤ ਕਰੋ', saveProfile: 'ਪ੍ਰੋਫਾਈਲ ਸੁਰੱਖਿਅਤ ਕਰੋ',
        savingProfile: 'ਸੁਰੱਖਿਅਤ ਹੋ ਰਿਹਾ ਹੈ…',
    },
    mr: {
        dashboard: 'डॅशबोर्ड', market: 'बाजार', insights: 'अंतर्ज्ञान', settings: 'सेटिंग्ज',
        profile: 'प्रोफाइल', signOut: 'साइन आउट', backToDashboard: 'डॅशबोर्डवर परत',
        goodMorning: 'सुप्रभात', goodAfternoon: 'नमस्कार', goodEvening: 'शुभ संध्या',
        aiSubtitle: 'AI-आधारित बाजार माहितीसाठी तुमचे पीक आणि स्थान निवडा.',
        liveMarketData: 'लाइव्ह बाजार डेटा सक्रिय',
        selectCrop: 'पीक निवडा', location: 'स्थान', runAnalysis: 'विश्लेषण करा', analyzing: 'विश्लेषण होत आहे…',
        locationPlaceholder: 'उदा. पंजाब, भारत',
        priceTrend: 'किंमत कल', temperature: 'तापमान', humidity: 'आर्द्रता', bestMandi: 'सर्वोत्तम मंडी',
        weatherForecast: 'हवामान अंदाज', live: 'थेट',
        rainfall: 'पाऊस', wind: 'वारा', uvIndex: 'UV निर्देशांक',
        spoilageRisk: 'खराब होण्याचा धोका', risk: 'धोका',
        pricePrediction: 'किंमत अंदाज', dayForecast: '14-दिवस AI अंदाज',
        over14d: '14 दिवसांत',
        bestMandiOpp: 'सर्वोत्तम मंडी संधी',
        mandiSubtitle: 'अंतर, किंमत आणि मागणीवर आधारित सर्वोत्तम बाजार',
        confidence: 'विश्वास', predictedPrice: 'अनुमानित किंमत', expProfit: 'अनु. नफा/एकर',
        aiConfidence: 'AI विश्वास', navigateToMandi: 'मंडीस जा',
        aiInsights: 'AI अंतर्ज्ञान', gptPowered: 'GPT-चालित',
        defaultInsight: 'ऐतिहासिक कलांनुसार आणि सध्याच्या मागणीनुसार, खन्ना मंडी स्थानिक सरासरीपेक्षा 12% जास्त दर दाखवत आहे.',
        demandSpike: 'मागणी वाढ', weatherRisk: 'हवामान धोका', historicalHigh: 'ऐतिहासिक उच्च',
        priceWindow: 'किंमत संधी', marketTrend: 'बाजार कल',
        saveSettings: 'सेटिंग्ज सेव्ह करा', saving: 'सेव्ह होत आहे…',
        notifications: 'सूचना', displayLanguage: 'प्रदर्शन आणि भाषा',
        privacyData: 'गोपनीयता आणि डेटा', dangerZone: 'धोकादायक क्षेत्र',
        theme: 'थीम', language: 'भाषा', languageSub: 'तुमची पसंतीची भाषा निवडा',
        light: 'हलकी', system: 'सिस्टम', dark: 'गडद',
        emailAlerts: 'ईमेल अलर्ट', emailAlertsSub: 'ईमेलद्वारे किंमत अपडेट मिळवा',
        smsAlerts: 'SMS अलर्ट', smsAlertsSub: 'फोनवर महत्त्वाचे अलर्ट मिळवा',
        priceDropAlerts: 'किंमत घसरण अलर्ट', priceDropAlertsSub: 'पीक किंमत घसरल्यावर सूचित करा',
        weeklyReport: 'साप्ताहिक बाजार अहवाल', weeklyReportSub: 'दर सोमवारी सकाळी सारांश ईमेल',
        marketNews: 'बाजार बातम्या', marketNewsSub: 'कृषी बातम्या आणि धोरण अपडेट',
        shareData: 'वापर डेटा शेअर करा', shareDataSub: 'CropSense सुधारण्यात मदत करा',
        analytics: 'एनालिटिक्स', analyticsSub: 'कार्यक्षमता आणि त्रुटी ट्रॅकिंगला परवानगी द्या',
        locationTracking: 'स्थान ट्रॅकिंग', locationTrackingSub: 'हवामान अचूकतेसाठी स्थान आपोआप ओळखा',
        deleteAccount: 'खाते हटवा', deleteAccountSub: 'तुमचे खाते आणि सर्व डेटा कायमचा हटवला जाईल.',
        delete: 'हटवा', cancel: 'रद्द करा', confirmDelete: 'तुमचे खाते हटवायचे?',
        confirmDeleteBody: 'तुमचा सर्व डेटा आणि प्राधान्ये कायमची काढून टाकली जातील.',
        marketPrices: 'बाजार भाव', commodityPrices: 'वस्तू किंमती',
        lastUpdated: 'शेवटचे अद्यतन', viewAll: 'सर्व पहा', pricePerQtl: '₹/क्विंटल',
        searchPlaceholder: 'पीक किंवा मंडी शोधा…',
        topGainer: 'सर्वाधिक वाढ', topLoser: 'सर्वाधिक घसरण', activeMandis: 'सक्रिय मंड्या', totalVolume: 'एकूण मात्रा',
        sixMonthTrend: '6 महिने किंमत कल', topMandisByVol: 'मात्रेनुसार शीर्ष मंड्या',
        marketNewsAlerts: 'बाजार बातम्या आणि अलर्ट',
        dataFooter: 'डेटा दर 30 मिनिटांनी अपडेट · CropSense AI © ',
        pricesIndicative: '· किंमती सांकेतिक आहेत',
        editProfile: 'प्रोफाइल संपादित करा', fullName: 'पूर्ण नाव', email: 'ईमेल',
        phoneNumber: 'फोन नंबर', locationLabel: 'स्थान', preferredCrop: 'पसंतीचे पीक',
        shortBio: 'संक्षिप्त माहिती', bioPlaceholder: 'तुमच्या शेताबद्दल सांगा…',
        accountInfo: 'खाते माहिती', accountType: 'खाते प्रकार', memberSince: 'सदस्यत्व तारीख',
        analysesRun: 'विश्लेषणे केली', avgAccuracy: 'सरासरी अचूकता',
        activeFarmer: 'सक्रिय शेतकरी', managePlan: 'योजना व्यवस्थापित करा', saveProfile: 'प्रोफाइल सेव्ह करा',
        savingProfile: 'सेव्ह होत आहे…',
    },
    gu: {
        dashboard: 'ડૅશબોર્ડ', market: 'બજાર', insights: 'આંતરદૃષ્ટિ', settings: 'સેટિંગ્સ',
        profile: 'પ્રોફાઇલ', signOut: 'સાઇન આઉટ', backToDashboard: 'ડૅશબોર્ડ પર પાછા',
        goodMorning: 'સુપ્રભાત', goodAfternoon: 'નમસ્કાર', goodEvening: 'શુભ સાંજ',
        aiSubtitle: 'AI-આધારિત બજાર માહિતી માટે તમારો પાક અને સ્થળ પસંદ કરો.',
        liveMarketData: 'લાઇવ બજાર ડેટા સક્રિય',
        selectCrop: 'પાક પસંદ કરો', location: 'સ્થળ', runAnalysis: 'વિશ્લેષણ કરો', analyzing: 'વિશ્લેષણ થઈ રહ્યું છે…',
        locationPlaceholder: 'દા.ત. પંજાબ, ભારત',
        priceTrend: 'ભાવ વલણ', temperature: 'તાપમાન', humidity: 'ભેજ', bestMandi: 'શ્રેષ્ઠ મંડી',
        weatherForecast: 'હવામાન અંદાજ', live: 'લાઇવ',
        rainfall: 'વરસાદ', wind: 'પવન', uvIndex: 'UV સૂચકાંક',
        spoilageRisk: 'બગડવાનો જોખમ', risk: 'જોખમ',
        pricePrediction: 'ભાવ અંદાજ', dayForecast: '14-દિવસ AI અંદાજ',
        over14d: '14 દિવસોમાં',
        bestMandiOpp: 'શ્રેષ્ઠ મંડી તક',
        mandiSubtitle: 'અંતર, ભાવ અને માંગ આધારે સ્રેષ્ઠ બજાર',
        confidence: 'વિશ્વાસ', predictedPrice: 'અંદાજિત ભાવ', expProfit: 'અં. નફો/એકર',
        aiConfidence: 'AI વિશ્વાસ', navigateToMandi: 'મંડી પર જાઓ',
        aiInsights: 'AI આંતરદૃષ્ટિ', gptPowered: 'GPT-સંચાલિત',
        defaultInsight: 'ઐતિહાસિક વલણો અને વર્તમાન માંગ અનુસાર, ખન્ના મંડી સ્થાનિક સરેરાશ કરતાં 12% વધુ ભાવ દર્શાવે છે.',
        demandSpike: 'માંગ વધારો', weatherRisk: 'હવામાન જોખમ', historicalHigh: 'ઐતિહાસિક ઊંચ',
        priceWindow: 'ભાવ તક', marketTrend: 'બજાર વલણ',
        saveSettings: 'સેટિંગ્સ સાચવો', saving: 'સાચવાઈ રહ્યું છે…',
        notifications: 'સૂચનાઓ', displayLanguage: 'પ્રદર્શન અને ભાષા',
        privacyData: 'ગોપનીયતા અને ડેટા', dangerZone: 'ખતરનાક ઝોન',
        theme: 'થીમ', language: 'ભાષા', languageSub: 'તમારી પ્રિય ભાષા પસંદ કરો',
        light: 'હળવી', system: 'સિસ્ટમ', dark: 'ઘેરી',
        emailAlerts: 'ઇમેઇલ અલર્ટ', emailAlertsSub: 'ઇમેઇલ દ્વારા ભાવ અપડેટ મેળવો',
        smsAlerts: 'SMS અલર્ટ', smsAlertsSub: 'ફોન પર મહત્ત્વના અલર્ટ મેળવો',
        priceDropAlerts: 'ભાવ ઘટાડો અલર્ટ', priceDropAlertsSub: 'પાક ભાવ ઘટે ત્યારે સૂચિત કરો',
        weeklyReport: 'સાપ્તાહિક બજાર અહેવાલ', weeklyReportSub: 'દર સોમવારે સવારે સારાંશ ઇમેઇલ',
        marketNews: 'બજાર સમાચાર', marketNewsSub: 'કૃષિ સમાચાર અને નીતિ અપડેટ',
        shareData: 'ઉપયોગ ડેટા શેર કરો', shareDataSub: 'CropSense સુધારવામાં મદદ કરો',
        analytics: 'એનાલિટિક્સ', analyticsSub: 'પ્રદર્શન અને ભૂલ ટ્રૅકિંગ માટે પરવાનગી',
        locationTracking: 'સ્થળ ટ્રૅકિંગ', locationTrackingSub: 'હવામાન ચોકસાઈ માટે સ્થળ આપોઆપ ઓળખો',
        deleteAccount: 'ખાતું કાઢો', deleteAccountSub: 'તમારું ખાતું અને ડેટા કાયમ માટે કાઢવામાં આવશે.',
        delete: 'કાઢો', cancel: 'રદ કરો', confirmDelete: 'તમારું ખાતું કાઢવું?',
        confirmDeleteBody: 'તમારો તમામ ડેટા અને પ્રાધાન્ય કાયમ માટે દૂર કરવામાં આવશે.',
        marketPrices: 'બજાર ભાવ', commodityPrices: 'ચીજ-વસ્તુ ભાવ',
        lastUpdated: 'છેલ્લું અપડેટ', viewAll: 'બધું જુઓ', pricePerQtl: '₹/ક્વિન્ટલ',
        searchPlaceholder: 'પાક અથવા મંડી શોધો…',
        topGainer: 'સૌથી વધુ વધારો', topLoser: 'સૌથી વધુ ઘટાડો', activeMandis: 'સક્રિય મંડ્ઓ', totalVolume: 'કુલ જથ્થો',
        sixMonthTrend: '6 માસ ભાવ વલણ', topMandisByVol: 'જથ્થા અનુસાર ટોચની મંડ્ઓ',
        marketNewsAlerts: 'બજાર સમાચાર અને અલર્ટ',
        dataFooter: 'ડેટા દર 30 મિનિટે અપડેટ · CropSense AI © ',
        pricesIndicative: '· ભાવ સૂચક છે',
        editProfile: 'પ્રોફાઇલ સંપાદિત કરો', fullName: 'પૂરું નામ', email: 'ઇમેઇલ',
        phoneNumber: 'ફોન નંબર', locationLabel: 'સ્થળ', preferredCrop: 'પ્રિય પાક',
        shortBio: 'સંક્ષિપ્ત પરિચય', bioPlaceholder: 'તમારા ખેત વિશે જણાવો…',
        accountInfo: 'ખાતા માહિતી', accountType: 'ખાતા પ્રકાર', memberSince: 'સભ્ય તારીખ',
        analysesRun: 'વિશ્લેષણ થયેલ', avgAccuracy: 'સરેરાશ ચોકસાઈ',
        activeFarmer: 'સક્રિય ખેડૂત', managePlan: 'પ્લાન મેનેજ કરો', saveProfile: 'પ્રોફાઇલ સાચવો',
        savingProfile: 'સાચવાઈ રહ્યું છે…',
    },
    te: {
        dashboard: 'డాష్‌బోర్డ్', market: 'మార్కెట్', insights: 'అంతర్దృష్టి', settings: 'సెట్టింగులు',
        profile: 'ప్రొఫైల్', signOut: 'సైన్ అవుట్', backToDashboard: 'డాష్‌బోర్డ్‌కు తిరిగి',
        goodMorning: 'శుభోదయం', goodAfternoon: 'నమస్కారం', goodEvening: 'శుభ సాయంత్రం',
        aiSubtitle: 'AI-ఆధారిత మార్కెట్ సమాచారం కోసం మీ పంట మరియు స్థానం ఎంచుకోండి.',
        liveMarketData: 'లైవ్ మార్కెట్ డేటా సక్రియంగా ఉంది',
        selectCrop: 'పంట ఎంచుకోండి', location: 'స్థానం', runAnalysis: 'విశ్లేషణ చేయండి', analyzing: 'విశ్లేషిస్తోంది…',
        locationPlaceholder: 'ఉదా. పంజాబ్, భారతదేశం',
        priceTrend: 'ధర ధోరణి', temperature: 'ఉష్ణోగ్రత', humidity: 'తేమ', bestMandi: 'అత్యుత్తమ మండీ',
        weatherForecast: 'వాతావరణ సూచన', live: 'లైవ్',
        rainfall: 'వర్షపాతం', wind: 'గాలి', uvIndex: 'UV సూచిక',
        spoilageRisk: 'పాడవడం ప్రమాదం', risk: 'ప్రమాదం',
        pricePrediction: 'ధర అంచనా', dayForecast: '14-రోజుల AI అంచనా',
        over14d: '14 రోజులలో',
        bestMandiOpp: 'అత్యుత్తమ మండీ అవకాశం',
        mandiSubtitle: 'దూరం, ధర మరియు డిమాండ్ ఆధారంగా అత్యుత్తమ మార్కెట్',
        confidence: 'నమ్మకం', predictedPrice: 'అంచనా ధర', expProfit: 'అం. లాభం/ఎకరం',
        aiConfidence: 'AI నమ్మకం', navigateToMandi: 'మండీకి వెళ్ళండి',
        aiInsights: 'AI అంతర్దృష్టి', gptPowered: 'GPT-ఆధారిత',
        defaultInsight: 'చారిత్రక ధోరణులు మరియు ప్రస్తుత డిమాండ్ ఆధారంగా, ఖన్నా మండీ స్థానిక సగటు కంటే 12% ఎక్కువ రేటు చూపుతోంది.',
        demandSpike: 'డిమాండ్ పెరుగుదల', weatherRisk: 'వాతావరణ ప్రమాదం', historicalHigh: 'చారిత్రక గరిష్ఠం',
        priceWindow: 'ధర అవకాశం', marketTrend: 'మార్కెట్ ధోరణి',
        saveSettings: 'సెట్టింగులు సేవ్ చేయండి', saving: 'సేవ్ అవుతోంది…',
        notifications: 'నోటిఫికేషన్లు', displayLanguage: 'ప్రదర్శన మరియు భాష',
        privacyData: 'గోప్యత మరియు డేటా', dangerZone: 'ప్రమాదకర జోన్',
        theme: 'థీమ్', language: 'భాష', languageSub: 'మీకు ఇష్టమైన భాష ఎంచుకోండి',
        light: 'లేత', system: 'సిస్టమ్', dark: 'చీకటి',
        emailAlerts: 'ఇమెయిల్ అలర్ట్లు', emailAlertsSub: 'ఇమెయిల్ ద్వారా ధర అప్‌డేట్లు పొందండి',
        smsAlerts: 'SMS అలర్ట్లు', smsAlertsSub: 'ఫోన్‌లో ముఖ్యమైన అలర్ట్లు పొందండి',
        priceDropAlerts: 'ధర తగ్గుదల అలర్ట్లు', priceDropAlertsSub: 'పంట ధర తగ్గినప్పుడు తెలియజేయండి',
        weeklyReport: 'వారపు మార్కెట్ నివేదిక', weeklyReportSub: 'ప్రతి సోమవారం ఉదయం సారాంశ ఇమెయిల్',
        marketNews: 'మార్కెట్ వార్తలు', marketNewsSub: 'వ్యవసాయ వార్తలు మరియు విధాన అప్‌డేట్లు',
        shareData: 'వినియోగ డేటా పంచుకోండి', shareDataSub: 'CropSense మెరుగుపరచడంలో సహాయం చేయండి',
        analytics: 'అనలిటిక్స్', analyticsSub: 'పనితీరు మరియు లోపం ట్రాకింగ్‌ను అనుమతించండి',
        locationTracking: 'స్థాన ట్రాకింగ్', locationTrackingSub: 'వాతావరణ ఖచ్చితత్వం కోసం స్థానం స్వయంచాలకంగా గుర్తించండి',
        deleteAccount: 'ఖాతా తొలగించండి', deleteAccountSub: 'మీ ఖాతా మరియు డేటా శాశ్వతంగా తొలగించబడుతుంది.',
        delete: 'తొలగించండి', cancel: 'రద్దు చేయండి', confirmDelete: 'మీ ఖాతా తొలగించాలా?',
        confirmDeleteBody: 'మీ అన్ని డేటా మరియు ప్రాధాన్యతలు శాశ్వతంగా తొలగించబడతాయి.',
        marketPrices: 'మార్కెట్ ధరలు', commodityPrices: 'వస్తు ధరలు',
        lastUpdated: 'చివరిసారి నవీకరించబడింది', viewAll: 'అన్నీ చూడండి', pricePerQtl: '₹/క్వింటల్',
        searchPlaceholder: 'పంట లేదా మండీ వెతకండి…',
        topGainer: 'అత్యధిక పెరుగుదల', topLoser: 'అత్యధిక తగ్గుదల', activeMandis: 'యాక్టివ్ మండీలు', totalVolume: 'మొత్తం పరిమాణం',
        sixMonthTrend: '6 నెలల ధర ధోరణి', topMandisByVol: 'పరిమాణం ప్రకారం టాప్ మండీలు',
        marketNewsAlerts: 'మార్కెట్ వార్తలు & అలర్ట్లు',
        dataFooter: 'డేటా ప్రతి 30 నిమిషాలకు అప్‌డేట్ · CropSense AI © ',
        pricesIndicative: '· ధరలు సూచనాత్మకమైనవి',
        editProfile: 'ప్రొఫైల్ సవరించండి', fullName: 'పూర్తి పేరు', email: 'ఇమెయిల్',
        phoneNumber: 'ఫోన్ నంబర్', locationLabel: 'స్థానం', preferredCrop: 'ఇష్టమైన పంట',
        shortBio: 'సంక్షిప్త పరిచయం', bioPlaceholder: 'మీ భూమి గురించి చెప్పండి…',
        accountInfo: 'ఖాతా సమాచారం', accountType: 'ఖాతా రకం', memberSince: 'సభ్యత్వ తేదీ',
        analysesRun: 'విశ్లేషణలు చేశారు', avgAccuracy: 'సగటు ఖచ్చితత్వం',
        activeFarmer: 'యాక్టివ్ రైతు', managePlan: 'ప్లాన్ నిర్వహించండి', saveProfile: 'ప్రొఫైల్ సేవ్ చేయండి',
        savingProfile: 'సేవ్ అవుతోంది…',
    },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(() => localStorage.getItem('cropsense_lang') || 'en');
    const setLanguage = (code) => { setLang(code); localStorage.setItem('cropsense_lang', code); };
    const t = (key) => T[lang]?.[key] ?? T.en[key] ?? key;
    return (
        <LanguageContext.Provider value={{ lang, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() { return useContext(LanguageContext); }
